### ISSUE TITLE
Error in Android Module Application doesn't have any In-Apps

### ISSUE THREAD

**Issue by abada** [Pushwoosh/pushwoosh-appcelerator-titanium#23]
I just used `V1.3.1` android module , and i have an issue 

```
[ERROR] Pushwoosh: [RequestManager] ERROR: {"status_code":210,"status_message":"Application doesn't have any In-Apps","response":null}. Response = {"status_code":210,"status_message":"Application doesn't have any In-Apps","response":null}
[ERROR] Pushwoosh: java.lang.Exception: {"status_code":210,"status_message":"Application doesn't have any In-Apps","response":null}
[ERROR] Pushwoosh:  at com.pushwoosh.internal.request.RequestManager.sendRequestSync(RequestManager.java:240)
[ERROR] Pushwoosh:  at com.pushwoosh.inapp.InAppRetrieverService.onHandleIntent(InAppRetrieverService.java:39)
[ERROR] Pushwoosh:  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
[ERROR] Pushwoosh:  at android.os.Handler.dispatchMessage(Handler.java:111)
[ERROR] Pushwoosh:  at android.os.Looper.loop(Looper.java:214)
[ERROR] Pushwoosh:  at android.os.HandlerThread.run(HandlerThread.java:61)
```

and the app crashed !

I have `Ti SDK 5.2.2.GA`

**Comment by DimanAM** [comment]
This error cannot cause crash. There should be something else in the log.

**Comment by beaur** [comment]
I get this error as well, however it doesn't cause the app to crash.  Ti SDK v5.3.0.v20160421080259

**Comment by shaders** [comment]
This error is harmless. You can safely ignore it.

**Comment by abada** [comment]
After using latest `ti sdk 5.3.0.v20160503133640`

This error shown 

```
[ERROR] AndroidRuntime: FATAL EXCEPTION: IntentService[GCMRegistrationService]
[ERROR] AndroidRuntime: Process: com.emoney.salla, PID: 13912
[ERROR] AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
[ERROR] AndroidRuntime:     at com.pushwoosh.GCMRegistrationService.register(GCMRegistrationService.java:37)
[ERROR] AndroidRuntime:     at com.pushwoosh.GCMRegistrationService.onHandleIntent(GCMRegistrationService.java:106)
[ERROR] AndroidRuntime:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
[ERROR] AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:111)
[ERROR] AndroidRuntime:     at android.os.Looper.loop(Looper.java:214)
[ERROR] AndroidRuntime:     at android.os.HandlerThread.run(HandlerThread.java:61)
[ERROR] AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.emoney.salla-1/base.apk"],nativeLibraryDirectories=[/data/app/com.emoney.salla-1/lib/arm, /vendor/lib, /system/lib]]
[ERROR] AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[ERROR] AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[ERROR] AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[ERROR] AndroidRuntime:     ... 6 more
[ERROR] AndroidRuntime:     Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
[ERROR] AndroidRuntime:         at java.lang.Class.classForName(Native Method)
[ERROR] AndroidRuntime:         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
[ERROR] AndroidRuntime:         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
[ERROR] AndroidRuntime:         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
[ERROR] AndroidRuntime:         ... 7 more
[ERROR] AndroidRuntime:     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by shaders** [comment]
You are using old google-play-services.jar which doesn't have com.google.android.gms.iid.InstanceID definition.

**Comment by abada** [comment]
When using `google-play-services.jar` which attached with pushwoosh module , i can not run my app , it freezes at 

```
[INFO]  Running dexer: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java "-Xmx1024M" ....
```

I am using `analytics.google 3.2.0` and `ti.map 2.3.10` 
How can make my app works with all these modules , specially every module used different `google-play-services.jar` version :(

**Comment by shaders** [comment]
dexer takes incredibly long long long long long time with google-play-services.jar (thanks Google). Please be patient.

**Comment by abada** [comment]
Ok thank you , i will try again

**Comment by abada** [comment]
dexer still running :(  time elapsed 20 Minutes !

**Comment by DimanAM** [comment]
Here is related thread: https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/issues/15
You can try shrinking google-play-services.jar for example using play-services*.jar from https://github.com/Pushwoosh/pushwoosh-xamarin/tree/master/Android/PushwooshSDK/Jars instead of google-play-services.jar
