### ISSUE TITLE
PushWoosh module 1.3.2 is crashing on android version 4.3

### ISSUE THREAD

**Issue by perdona** [Pushwoosh/pushwoosh-appcelerator-titanium#27]
Hi, I'm getting this error below on Android 4.3. 

`[WARN]  dalvikvm: VFY: unable to resolve static method 128: Landroid/app/ActivityOptions;.makeSceneTransitionAnimation (Landroid/app/Activity;[Landroid/util/Pair;)Landroid/app/ActivityOptions;
[WARN]  W/System.err: java.lang.NullPointerException
[WARN]  W/System.err:   at com.pushwoosh.module.PushnotificationsModule.unregister(PushnotificationsModule.java:285)
[WARN]  W/System.err:   at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[WARN]  W/System.err:   at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
[WARN]  W/System.err:   at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:319)
[WARN]  W/System.err:   at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)
[WARN]  W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN]  W/System.err:   at android.os.Looper.loop(Looper.java:176)
[WARN]  W/System.err:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:118)
[ERROR] TiExceptionHandler: (main) [26,879] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,879] - In services.js:1,69
[ERROR] TiExceptionHandler: (main) [0,879] - Message: Uncaught Error: Java Exception occurred
[ERROR] TiExceptionHandler: (main) [0,879] - Source: uire("push")(t);e.open()},1e3)}})},exports.stopPush=function(){push.unregister
[ERROR] V8Exception: Exception occurred at services.js:1: Uncaught Error: Java Exception occurred`

On greater versions, app is running normally.
I'm using Titanium 5.2.2.GA with PushWoosh module version 1.3.2

Can you help me with this?
Thanks in advance.

**Comment by perdona** [comment]
Actually, error is happening on all Android versions.
I updated the module 4 days ago, it worked for a while, then it started crashing the app showing the error above.
