### ISSUE TITLE
Version 5.5.2. crashes app on SDK 7.0.1.GA (Android)

### ISSUE THREAD

**Issue by arifje** [Pushwoosh/pushwoosh-appcelerator-titanium#54]
Hi,

The current version seems to cause a crash on SDK 7.0.1.GA:

```
[INFO] :   Pushwoosh: [PushwooshPlatform] This is Android GCM device
[WARN] :   TiAndroid: (main) [1777,1861] Application instance no longer available. Unable to get current activity.
[WARN] :   TiAndroid: (main) [1,1862] Application instance no longer available. Unable to get current activity.
[WARN] :   TiAndroid: (main) [0,1862] Application instance no longer available. Unable to get current activity.
[ERROR] :  TiApplication: (main) [17,1879] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt3__112__next_primeEj" referenced by "/data/app/test.com.mo-2/lib/arm/libcom.pushwoosh.module.so"...; Titanium 7.0.1,2017/12/18 10:42,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt3__112__next_primeEj" referenced by "/data/app/test.com.mo-2/lib/arm/libcom.pushwoosh.module.so"...
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:1567)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] :  TiApplication: 	at test.com.mo.TestApplication.onCreate(TestApplication.java:49)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:154)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

Native log;

```
12-26 17:22:19.451 13050 13050 D Pushwoosh: [PushwooshModule] onApplicationCreated
12-26 17:22:19.452 13050 13050 I Pushwoosh: [PushwooshPlatform] This is Android GCM device
12-26 17:22:19.710  2924  2924 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 839000  uid : 1000  pid : 2924  tag : GESTURE_DETECTE
D@CPU_MIN@38
12-26 17:22:19.745  3249  3249 D ImageWallpaper: onVisibilityChanged: mVisible=true visible=false
12-26 17:22:19.745  3249  3249 D ImageWallpaper: Visibility changed to visible=false
12-26 17:22:19.761  3726  3726 D io_stats: !@ 179,0 r 75687 4342866 w 17002 466504 d 1745 148596 f 5849 5848 iot 60730 59309 th 51200 0 0 pt 0 inp 0 0 2437.078
12-26 17:22:19.801  2924  3070 D SensorService: [SO] -0.866 -0.063 9.782
12-26 17:22:20.981 13050 13050 W TiAndroid: (main) [1565,1639] Application instance no longer available. Unable to get current activity.
12-26 17:22:20.983 13050 13050 W TiAndroid: (main) [2,1641] Application instance no longer available. Unable to get current activity.
12-26 17:22:20.983 13050 13050 W TiAndroid: (main) [0,1641] Application instance no longer available. Unable to get current activity.
12-26 17:22:21.001 13050 13050 D AndroidRuntime: Shutting down VM
12-26 17:22:21.001 13050 13050 E TiApplication: (main) [18,1659] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt3__112__next_p
rimeEj" referenced by "/data/app/test.com.mo-2/lib/arm/libcom.pushwoosh.module.so"...; Titanium 7.0.1,2017/12/18 10:42,undefined
12-26 17:22:21.001 13050 13050 E TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt3__112__next_primeEj" referenced by "/data/app/test.com.mo-2/lib/arm/libcom.
pushwoosh.module.so"...
12-26 17:22:21.001 13050 13050 E TiApplication:         at java.lang.Runtime.loadLibrary0(Runtime.java:977)
12-26 17:22:21.001 13050 13050 E TiApplication:         at java.lang.System.loadLibrary(System.java:1567)
12-26 17:22:21.001 13050 13050 E TiApplication:         at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
12-26 17:22:21.001 13050 13050 E TiApplication:         at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
12-26 17:22:21.001 13050 13050 E TiApplication:         at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
12-26 17:22:21.001 13050 13050 E TiApplication:         at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
12-26 17:22:21.001 13050 13050 E TiApplication:         at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
12-26 17:22:21.001 13050 13050 E TiApplication:         at test.com.mo.TestApplication.onCreate(TestApplication.java:49)
12-26 17:22:21.001 13050 13050 E TiApplication:         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
12-26 17:22:21.001 13050 13050 E TiApplication:         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
12-26 17:22:21.001 13050 13050 E TiApplication:         at android.app.ActivityThread.-wrap3(ActivityThread.java)
12-26 17:22:21.001 13050 13050 E TiApplication:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
12-26 17:22:21.001 13050 13050 E TiApplication:         at android.os.Handler.dispatchMessage(Handler.java:102)
12-26 17:22:21.001 13050 13050 E TiApplication:         at android.os.Looper.loop(Looper.java:154)
12-26 17:22:21.001 13050 13050 E TiApplication:         at android.app.ActivityThread.main(ActivityThread.java:6776)
12-26 17:22:21.001 13050 13050 E TiApplication:         at java.lang.reflect.Method.invoke(Native Method)
12-26 17:22:21.001 13050 13050 E TiApplication:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
12-26 17:22:21.001 13050 13050 E TiApplication:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
12-26 17:22:21.020 13050 13050 E AndroidRuntime: FATAL EXCEPTION: main
12-26 17:22:21.020 13050 13050 E AndroidRuntime: Process: test.com.mo, PID: 13050
12-26 17:22:21.020 13050 13050 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt3__112__next_primeEj" referenced by "/data/app/test.com.mo-2/lib/arm/libcom
.pushwoosh.module.so"...
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1567)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at test.com.mo.TestApplication.onCreate(TestApplication.java:49)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at android.app.ActivityThread.-wrap3(ActivityThread.java)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6776)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
12-26 17:22:21.020 13050 13050 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
12-26 17:22:21.021  2924  4052 D Debug   : !@DumpState : SHIP
12-26 17:22:21.022  2924  4052 D Debug   : !@DumpState : debug level:0x4f4c
12-26 17:22:21.022  2924  4052 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
```

Tested on a new/clean project with ti.playservices installed.
Platform: Android

**Comment by wfhm** [comment]
Hi,

There was an issue on the build server. A new build was released, so it should be fixed now. Please let us know about the results.

Also, the latest plugin version is just rolled out, so might try it out as well.
