### ISSUE TITLE
App crashed during startup on Android 4.X.X version

### ISSUE THREAD

**Issue by arifje** [Pushwoosh/pushwoosh-appcelerator-titanium#56]
Again, the app crashes on startup...this time it's on older versions of Android: 4.X.X.

Tested on a real device (S4 mini with Android 4.4.2)

ADB log:

```
I/TiApplication(16788): (main) [378,378] Titanium 7.0.1 (2017/12/18 10:42 undefined)
I/MultiDex(16788): VM with version 1.6.0 does not have multidex support
I/MultiDex(16788): install
I/MultiDex(16788): MultiDexExtractor.load(/data/app/pushwoosh.test.com-1.apk, false)
I/MultiDex(16788): loading existing secondary dex files
I/MultiDex(16788): load found 0 secondary dex files
I/MultiDex(16788): install done
I/dalvikvm(16788): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zzo.zzy
W/dalvikvm(16788): VFY: unable to resolve virtual method 830: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm(16788): VFY: replacing opcode 0x6e at 0x0012
D/AndroidRuntime(16788): Shutting down VM
W/dalvikvm(16788): threadid=1: thread exiting with uncaught exception (group=0x4191cda0)
E/AndroidRuntime(16788): FATAL EXCEPTION: main
E/AndroidRuntime(16788): Process: pushwoosh.test.com, PID: 16788
E/AndroidRuntime(16788): java.lang.RuntimeException: Unable to get provider com.pushwoosh.gcm.GcmInitProvider: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right va
lue.  Expected 11020000 but found 11400000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_servic
es_version" />
E/AndroidRuntime(16788):        at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
E/AndroidRuntime(16788):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4827)
E/AndroidRuntime(16788):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
E/AndroidRuntime(16788):        at android.app.ActivityThread.access$1600(ActivityThread.java:174)
E/AndroidRuntime(16788):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
E/AndroidRuntime(16788):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(16788):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(16788):        at android.app.ActivityThread.main(ActivityThread.java:5593)
E/AndroidRuntime(16788):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(16788):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(16788):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(16788):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(16788):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(16788): Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 11020000 but found 11400000.  You must have the following de
claration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
E/AndroidRuntime(16788):        at com.google.android.gms.common.zzo.isGooglePlayServicesAvailable(Unknown Source)
E/AndroidRuntime(16788):        at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
E/AndroidRuntime(16788):        at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
E/AndroidRuntime(16788):        at com.pushwoosh.gcm.a.b.b(Unknown Source)
E/AndroidRuntime(16788):        at com.pushwoosh.gcm.a.b.check(Unknown Source)
E/AndroidRuntime(16788):        at com.pushwoosh.gcm.GcmInitProvider.a(Unknown Source)
E/AndroidRuntime(16788):        at com.pushwoosh.gcm.GcmInitProvider.onCreate(Unknown Source)
E/AndroidRuntime(16788):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime(16788):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime(16788):        at android.app.ActivityThread.installProvider(ActivityThread.java:5233)
E/AndroidRuntime(16788):        ... 12 more
W/ActivityManager(  757):   Force finishing activity pushwoosh.test.com/.PushwooshTestActivity
E/SMD     (  185): DCD ON
D/Sensors (  757): LightSensor readEvents x = 12.000000, raw = 12
I/Finsky  (16672): [1] com.google.android.finsky.verifier.impl.aq.c(55): Done restoring notifications
D/Sensors (  757): LightSensor readEvents x = 19.000000, raw = 19
D/STATUSBAR-NetworkController(  943): onSignalStrengthsChanged signalStrength=SignalStrength: 99 -1 -1 -1 -1 -1 -1 28 -83 -8 204 -1 2147483647 gsm|lte 0x3 level=3
I/WindowManager(  757): Screenshot max retries 4 of Token{437c6780 ActivityRecord{43390af0 u0 pushwoosh.test.com/.PushwooshTestActivity t78 f}} appWin=Window{42875388 u0 Starting pushwoosh.test.com} drawState=4
W/WindowManager(  757): Screenshot failure taking screenshot for (540x960) to layer 21060
D/Dialog  (  757):  checkMirrorLinkEnabled returns : false
D/Dialog  (  757): showing allowed
```
Tested on a clean Alloy project with latest module (5.5.3).
Using SDK 7.0.1.GA

Test project: https://ufile.io/3x1di

EDIT: apparently I had 5.5.2 added to to project. Looks like it's working with latest (5.5.3). You can close this.

**Comment by wfhm** [comment]
Hi,

Could you please try deleting the following string from your AndroidManifest.xml:

`<meta-data android:name="com.google.android.gms.version" android:value="11400000"/>`

Please let us know about the results.
